[package]
name = "cargo-expand"
version = "0.4.5"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Wrapper around rustc --pretty=expanded. Shows the result of macro expansion and #[derive] expansion."
repository = "https://github.com/dtolnay/cargo-expand"
documentation = "https://github.com/dtolnay/cargo-expand"
keywords = ["cargo", "subcommand", "expanded"]
categories = ["development-tools::cargo-plugins", "development-tools::debugging"]
edition = "2018"
readme = "README.md"

[dependencies]
atty = "0.2"
prettyprint = "0.3"
proc-macro2 = "0.4"
quote = { version = "0.6", default-features = false }
structopt = "0.2"
syn-select = "0.1"
tempfile = "3.0"
toolchain_find = "0.1"

[dependencies.syn]
version = "0.15"
default-features = false
features = ["full", "parsing", "printing", "visit-mut"]

[badges]
travis-ci = { repository = "dtolnay/cargo-expand" }
